name: Postman CI - Users-Login

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Verificar versão do Newman e Node.js
    - name: Check version Newman and Node
      run: |
        newman --version
        node --version

    # Instalar newman-reporter-htmlextra
    - name: Install Newman-Reporter-HtmlExtra
      run: |
        sudo npm install -g newman-reporter-htmlextra

    # Executar a coleção com ambiente especificado
    - name: Execute collection
      run: |
      
        newman run Supernatural/Users-Login/Auth.json -e Supernatural/Users-Login/Supernatural_QA-env.json  --reporters cli,htmlextra --reporter-htmlextra-export Supernatural/Users-Login/docs/index.html



    # Carregar relatório de teste
    - name: Upload Test Report
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: Supernatural/Users-Login/docs/index.html
